### ISSUE TITLE
feature request: render method argument data as json string

### ISSUE THREAD

**Issue by jorisdebock** [hedonCZ/jsreport-javaclient#5]
Would it be possible to add a render method where I can directly provide the data as a json string instead of a java object?

**Comment by hedonCZ** [comment]
This could be done quite easy using JSON deserialization. I added extra test which demonstrates it. Check this: https://github.com/hedonCZ/jsreport-javaclient/blob/49ad5a815a578fed90fe4ced50711c25a9bb293c/src/test/groovy/net/jsreport/java/service/JsReportServiceITSpec.groovy#L229
